const Images = {
    LOAD: 'LOAD_IMAGES',
    LOAD_IMAGE_SUCCESS: 'LOAD_IMAGE_SUCCESS',
    LOAD_IMAGE_FAILURE: 'LOAD_IMAGE_FAILURE',


    LOAD_STATS: 'LOAD_STATS',
    LOAD_STATS_SUCCESS: 'LOAD_STATS_SUCCESS',
    LOAD_STATS_FAILURE: 'LOAD_STATS_FAILURE'
}

export default Images;